# Modify from https://github.com/bitnami/bitnami-docker-jupyter-base-notebook/blob/master/docker-compose.yml

version: '2'
services:
  notebook:
    build: ./jupyter
    image: my-notebook
    container_name: ${NAME}
    volumes:
      - "work:/home/jovyan/work"
    ports:
      - "8888:8888"
    environment:
      PASSWORD: ${PASSWORD}
      VIRTUAL_PORT: 8888
    networks:
      - docker
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - docker
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=kylechou@stompy.io
    depends_on:
      - nginx-proxy
    networks:
      - docker

volumes:
  work:
  certs:
  vhost.d:
  html:
  acme:

networks:
  docker:
