---
- name: "Set time zone is {{ timezone }}"
  timezone:
    name: "{{ timezone }}"

- name: Disable swap
  shell: "swapoff -a && sysctl -w vm.swappiness=0"
  ignore_errors: true

- name: Delete swap config in fstab
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    state: absent
    backup: yes
