---
- name: Install apt packages for docker
  apt:
    name: '{{ item }}'
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: 'deb [arch=amd64] {{ docker_mirror_url | default("https://download.docker.com/linux/ubuntu") }} {{ ansible_lsb.codename | lower }} stable'
    state: present

- name: Update apt and install docker-ce
  apt:
    name: '{{ item }}'
    update_cache: yes
    state: present
  loop:
  - docker-ce
  - docker-ce-cli
  - containerd.io

- name: Add user to docker group
  user:
    name: ubuntu
    group: docker

- name: Setup docker registry mirror
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: '0755'
  when: docker_registry_url is defined
  notify: Restart docker
